// Marriage matching master data — static lookup values

export interface DropdownItem {
  text: string;
  textLocale: string;
  value: string;
}

export interface HeightItem {
  text: string;
  value: string;
}

export interface WeightItem {
  text: string;
  value: string;
}

export const DISTRICTS: DropdownItem[] = [
  { text: 'Alappuzha', textLocale: 'dis.alappuzha', value: '4' },
  { text: 'Ernakulam', textLocale: 'dis.ernakulam', value: '7' },
  { text: 'Idukki', textLocale: 'dis.idukki', value: '6' },
  { text: 'Kannur', textLocale: 'dis.kannur', value: '13' },
  { text: 'Kasargod', textLocale: 'dis.kasargod', value: '15' },
  { text: 'Kollam', textLocale: 'dis.kollam', value: '2' },
  { text: 'Kottayam', textLocale: 'dis.kottayam', value: '5' },
  { text: 'Kozhikode', textLocale: 'dis.kozhikode', value: '11' },
  { text: 'Malappuram', textLocale: 'dis.malappuram', value: '10' },
  { text: 'Palakkad', textLocale: 'dis.palakkad', value: '9' },
  { text: 'Pathanamthitta', textLocale: 'dis.pathanamthitta', value: '3' },
  { text: 'Thrissur', textLocale: 'dis.thrissur', value: '8' },
  { text: 'Trivandrum', textLocale: 'dis.trivandrum', value: '1' },
  { text: 'Wayanad', textLocale: 'dis.wayanad', value: '12' },
];

// Places keyed by district value — only districts with place data are listed
export const PLACES: Record<string, DropdownItem[]> = {
  '10': [
    { text: 'A R Nagar', textLocale: 'place.a_r_nagar', value: '101' },
    { text: 'Anakkayam', textLocale: 'place.anakkayam', value: '102' },
    { text: 'Angadipuram', textLocale: 'place.angadipuram', value: '103' },
    { text: 'Areekode', textLocale: 'place.areekode', value: '104' },
    { text: 'Ariyallur', textLocale: 'place.ariyallur', value: '105' },
    { text: 'AtavanadMalappuram', textLocale: 'place.atavanadmalappuram', value: '106' },
    { text: 'Changaramkulam', textLocale: 'place.changaramkulam', value: '107' },
    { text: 'Chelambra', textLocale: 'place.chelambra', value: '108' },
    { text: 'Chelari', textLocale: 'place.chelari', value: '109' },
    { text: 'Chemmad', textLocale: 'place.chemmad', value: '1010' },
    { text: 'ChengaraMalappuram', textLocale: 'place.chengaramalappuram', value: '1011' },
    { text: 'Cheriyamundam', textLocale: 'place.cheriyamundam', value: '1012' },
    { text: 'Cherukavu', textLocale: 'place.cherukavu', value: '1013' },
    { text: 'Chettippadi', textLocale: 'place.chettippadi', value: '1014' },
    { text: 'Chungathara', textLocale: 'place.chungathara', value: '1015' },
    { text: 'Edakkara', textLocale: 'place.edakkara', value: '1016' },
    { text: 'Edappal', textLocale: 'place.edappal', value: '1017' },
    { text: 'Edavanna', textLocale: 'place.edavanna', value: '1018' },
    { text: 'Edavannappara', textLocale: 'place.edavannappara', value: '1019' },
    { text: 'Ederikkodu', textLocale: 'place.ederikkodu', value: '1020' },
    { text: 'Eramangalam', textLocale: 'place.eramangalam', value: '1021' },
    { text: 'Irimbiliyam', textLocale: 'place.irimbiliyam', value: '1022' },
    { text: 'Irumbuzhi', textLocale: 'place.irumbuzhi', value: '1023' },
    { text: 'Kadampuzha', textLocale: 'place.kadampuzha', value: '1024' },
    { text: 'Kakkad', textLocale: 'place.kakkad', value: '1025' },
    { text: 'Kalikavu', textLocale: 'place.kalikavu', value: '1026' },
    { text: 'Kalpakanchery', textLocale: 'place.kalpakanchery', value: '1027' },
    { text: 'Karinkallathani', textLocale: 'place.karinkallathani', value: '1028' },
    { text: 'Karipur', textLocale: 'place.karipur', value: '1029' },
    { text: 'Karulai', textLocale: 'place.karulai', value: '1030' },
    { text: 'Karuvarakundu', textLocale: 'place.karuvarakundu', value: '1031' },
    { text: 'Kattipparuthi', textLocale: 'place.kattipparuthi', value: '1032' },
    { text: 'Kavanoor', textLocale: 'place.kavanoor', value: '1033' },
    { text: 'Kizhisseri', textLocale: 'place.kizhisseri', value: '1034' },
    { text: 'Kodinhi', textLocale: 'place.kodinhi', value: '1035' },
    { text: 'Kodur', textLocale: 'place.kodur', value: '1036' },
    { text: 'Kolappuram', textLocale: 'place.kolappuram', value: '1037' },
    { text: 'KolathurMalappuram', textLocale: 'place.kolathurmalappuram', value: '1038' },
    { text: 'Kondotty', textLocale: 'place.kondotty', value: '1039' },
    { text: 'Koottilangadi', textLocale: 'place.koottilangadi', value: '1040' },
    { text: 'Kottakkal', textLocale: 'place.kottakkal', value: '1041' },
    { text: 'Kottappuram', textLocale: 'place.kottappuram', value: '1042' },
    { text: 'Kozhichena', textLocale: 'place.kozhichena', value: '1043' },
    { text: 'kundukadavu junction', textLocale: 'place.kundukadavu_junction', value: '1044' },
    { text: 'Kunnumpuram', textLocale: 'place.kunnumpuram', value: '1045' },
    { text: 'Kuttippuram', textLocale: 'place.kuttippuram', value: '1046' },
    { text: 'Makkaraparamba', textLocale: 'place.makkaraparamba', value: '1047' },
    { text: 'Malappuram', textLocale: 'place.malappuram', value: '1049' },
    { text: 'Mampad', textLocale: 'place.mampad', value: '1050' },
    { text: 'Mampuram', textLocale: 'place.mampuram', value: '1051' },
    { text: 'Manjeri', textLocale: 'place.manjeri', value: '1052' },
    { text: 'Mankada', textLocale: 'place.mankada', value: '1053' },
    { text: 'Marancheri', textLocale: 'place.marancheri', value: '1054' },
    { text: 'Mayyerichira', textLocale: 'place.mayyerichira', value: '1055' },
    { text: 'Melattur', textLocale: 'place.melattur', value: '1056' },
    { text: 'Mongam', textLocale: 'place.mongam', value: '1057' },
    { text: 'Moonniyur', textLocale: 'place.moonniyur', value: '1058' },
    { text: 'Morayur', textLocale: 'place.morayur', value: '1059' },
    { text: 'Munderi', textLocale: 'place.munderi', value: '1060' },
    { text: 'Naduvattom', textLocale: 'place.naduvattom', value: '1061' },
    { text: 'Nannambra', textLocale: 'place.nannambra', value: '1062' },
    { text: 'Nariparamba', textLocale: 'place.nariparamba', value: '1063' },
    { text: 'Neduva', textLocale: 'place.neduva', value: '1064' },
    { text: 'Nilambur', textLocale: 'place.nilambur', value: '1065' },
    { text: 'Omanoor', textLocale: 'place.omanoor', value: '1066' },
    { text: 'Oorakam', textLocale: 'place.oorakam', value: '1067' },
    { text: 'Othukkungal', textLocale: 'place.othukkungal', value: '1068' },
    { text: 'Padapparamba', textLocale: 'place.padapparamba', value: '1069' },
    { text: 'Padikkal', textLocale: 'place.padikkal', value: '1070' },
    { text: 'Pallichal', textLocale: 'place.pallichal', value: '1071' },
    { text: 'Pallikkal', textLocale: 'place.pallikkal', value: '1072' },
    { text: 'Pandikkad', textLocale: 'place.pandikkad', value: '1073' },
    { text: 'Parappanangadi', textLocale: 'place.parappanangadi', value: '1074' },
    { text: 'Parappur', textLocale: 'place.parappur', value: '1075' },
    { text: 'Pattikkad', textLocale: 'place.pattikkad', value: '1076' },
    { text: 'Perinthalmanna', textLocale: 'place.perinthalmanna', value: '1077' },
    { text: 'Perumpadappu', textLocale: 'place.perumpadappu', value: '1078' },
    { text: 'Peruvallur', textLocale: 'place.peruvallur', value: '1079' },
    { text: 'Ponmala', textLocale: 'place.ponmala', value: '1080' },
    { text: 'Ponmundam', textLocale: 'place.ponmundam', value: '1081' },
    { text: 'Ponnani', textLocale: 'place.ponnani', value: '1082' },
    { text: 'Pookkottumpadam', textLocale: 'place.pookkottumpadam', value: '1083' },
    { text: 'Pookkottur', textLocale: 'place.pookkottur', value: '1084' },
    { text: 'Pulamanthole', textLocale: 'place.pulamanthole', value: '1085' },
    { text: 'Pulikkal', textLocale: 'place.pulikkal', value: '1086' },
    { text: 'Puthanathani', textLocale: 'place.puthanathani', value: '1087' },
    { text: 'Puthanpalli', textLocale: 'place.puthanpalli', value: '1088' },
    { text: 'Puthupparamba', textLocale: 'place.puthupparamba', value: '1089' },
    { text: 'Puzhambram', textLocale: 'place.puzhambram', value: '1090' },
    { text: 'Randathani', textLocale: 'place.randathani', value: '1091' },
    { text: 'Talakkad', textLocale: 'place.talakkad', value: '1092' },
    { text: 'Tanalur', textLocale: 'place.tanalur', value: '1093' },
    { text: 'Tanur', textLocale: 'place.tanur', value: '1094' },
    { text: 'Tavanur', textLocale: 'place.tavanur', value: '1095' },
    { text: 'Thalappara', textLocale: 'place.thalappara', value: '1096' },
    { text: 'Thenhippalam', textLocale: 'place.thenhippalam', value: '1097' },
    { text: 'Thennala', textLocale: 'place.thennala', value: '1098' },
    { text: 'Theyyalingal', textLocale: 'place.theyyalingal', value: '1099' },
    { text: 'Thirunavaya', textLocale: 'place.thirunavaya', value: '10100' },
    { text: 'Thootha', textLocale: 'place.thootha', value: '10101' },
    { text: 'Tirur', textLocale: 'place.tirur', value: '10102' },
    { text: 'Tirurangadi', textLocale: 'place.tirurangadi', value: '10103' },
    { text: 'Triprangode', textLocale: 'place.triprangode', value: '10104' },
    { text: 'Tuvvur', textLocale: 'place.tuvvur', value: '10105' },
    { text: 'Unniyal', textLocale: 'place.unniyal', value: '10106' },
    { text: 'Vadakkangara', textLocale: 'place.vadakkangara', value: '10107' },
    { text: 'Vailathur', textLocale: 'place.vailathur', value: '10108' },
    { text: 'valanchery', textLocale: 'place.valanchery', value: '10109' },
    { text: 'Vallikkunnu', textLocale: 'place.vallikkunnu', value: '10110' },
    { text: 'Vaniyambalam', textLocale: 'place.vaniyambalam', value: '10111' },
    { text: 'Vazhakkad', textLocale: 'place.vazhakkad', value: '10112' },
    { text: 'Vazhayur', textLocale: 'place.vazhayur', value: '10113' },
    { text: 'Vazhikkadavu', textLocale: 'place.vazhikkadavu', value: '10114' },
    { text: 'Velimukku', textLocale: 'place.velimukku', value: '10115' },
    { text: 'Veliyankode', textLocale: 'place.veliyankode', value: '10116' },
    { text: 'Vengad', textLocale: 'place.vengad', value: '10117' },
    { text: 'Vengara', textLocale: 'place.vengara', value: '10118' },
    { text: 'Venniyour', textLocale: 'place.venniyour', value: '10119' },
    { text: 'vettichira', textLocale: 'place.vettichira', value: '10120' },
    { text: 'Wandoor', textLocale: 'place.wandoor', value: '10121' },
  ],
  '11': [
    { text: 'Adivaram', textLocale: 'place.adivaram', value: '111' },
    { text: 'Arakkinarcalicut', textLocale: 'place.arakkinarcalicut', value: '112' },
    { text: 'Atholi', textLocale: 'place.atholi', value: '113' },
    { text: 'Ayancheri', textLocale: 'place.ayancheri', value: '114' },
    { text: 'Ayanikkad', textLocale: 'place.ayanikkad', value: '115' },
    { text: 'Azhiyur', textLocale: 'place.azhiyur', value: '116' },
    { text: 'Balusseri', textLocale: 'place.balusseri', value: '117' },
    { text: 'Beypore', textLocale: 'place.beypore', value: '119' },
    { text: 'Calicut', textLocale: 'place.calicut', value: '1111' },
    { text: 'Chaliyam', textLocale: 'place.chaliyam', value: '1113' },
    { text: 'Chekkiad', textLocale: 'place.chekkiad', value: '1114' },
    { text: 'Chelannur', textLocale: 'place.chelannur', value: '1115' },
    { text: 'Chemancheri', textLocale: 'place.chemancheri', value: '1116' },
    { text: 'Cheruvannur', textLocale: 'place.cheruvannur', value: '1117' },
    { text: 'Chorode', textLocale: 'place.chorode', value: '1118' },
    { text: 'Edacheri', textLocale: 'place.edacheri', value: '1119' },
    { text: 'Ekarool', textLocale: 'place.ekarool', value: '1120' },
    { text: 'Elathur', textLocale: 'place.elathur', value: '1121' },
    { text: 'Engapuzha', textLocale: 'place.engapuzha', value: '1122' },
    { text: 'Eramala', textLocale: 'place.eramala', value: '1123' },
    { text: 'Feroke', textLocale: 'place.feroke', value: '1124' },
    { text: 'Iringal', textLocale: 'place.iringal', value: '1125' },
    { text: 'Kadalundi', textLocale: 'place.kadalundi', value: '1126' },
    { text: 'kakkattil', textLocale: 'place.kakkattil', value: '1127' },
    { text: 'Kakkodi', textLocale: 'place.kakkodi', value: '1128' },
    { text: 'Kakkur', textLocale: 'place.kakkur', value: '1129' },
    { text: 'Kallachi', textLocale: 'place.kallachi', value: '1130' },
    { text: 'Kallai', textLocale: 'place.kallai', value: '1131' },
    { text: 'Kappad', textLocale: 'place.kappad', value: '1132' },
    { text: 'Karanthur', textLocale: 'place.karanthur', value: '1133' },
    { text: 'Karaparamba', textLocale: 'place.karaparamba', value: '1134' },
    { text: 'Karuvanthuruthy', textLocale: 'place.karuvanthuruthy', value: '1136' },
    { text: 'Keezhariyur', textLocale: 'place.keezhariyur', value: '1137' },
    { text: 'Kodencheri', textLocale: 'place.kodencheri', value: '1138' },
    { text: 'Kodiyathur', textLocale: 'place.kodiyathur', value: '1139' },
    { text: 'Koduvally', textLocale: 'place.koduvally', value: '1140' },
    { text: 'Kolathara', textLocale: 'place.kolathara', value: '1141' },
    { text: 'Kolathur', textLocale: 'place.kolathur', value: '1142' },
    { text: 'Koodaranhi', textLocale: 'place.koodaranhi', value: '1143' },
    { text: 'koorachundu', textLocale: 'place.koorachundu', value: '1144' },
    { text: 'Kottappally', textLocale: 'place.kottappally', value: '1145' },
    { text: 'Koyilandi', textLocale: 'place.koyilandi', value: '1146' },
    { text: 'Kozhikode', textLocale: 'place.kozhikode', value: '1147' },
    { text: 'Kozhukkallur', textLocale: 'place.kozhukkallur', value: '1148' },
    { text: 'Kunhippalli', textLocale: 'place.kunhippalli', value: '1149' },
    { text: 'Kunnamangalam', textLocale: 'place.kunnamangalam', value: '1150' },
    { text: 'Kunnummal', textLocale: 'place.kunnummal', value: '1151' },
    { text: 'Kuruvattur', textLocale: 'place.kuruvattur', value: '1152' },
    { text: 'Kuttiady', textLocale: 'place.kuttiady', value: '1153' },
    { text: 'Kuttikkattoor', textLocale: 'place.kuttikkattoor', value: '1154' },
    { text: 'Madavoor', textLocale: 'place.madavoor', value: '1156' },
    { text: 'Maniyur', textLocale: 'place.maniyur', value: '1157' },
    { text: 'Mankavu', textLocale: 'place.mankavu', value: '1158' },
    { text: 'Mavoor', textLocale: 'place.mavoor', value: '1159' },
    { text: 'Medical college', textLocale: 'place.medical_college', value: '1161' },
    { text: 'Meenchanda', textLocale: 'place.meenchanda', value: '1162' },
    { text: 'Meppayyur', textLocale: 'place.meppayyur', value: '1163' },
    { text: 'Moozhikkal', textLocale: 'place.moozhikkal', value: '1164' },
    { text: 'Mukkam', textLocale: 'place.mukkam', value: '1165' },
    { text: 'Nadapuram', textLocale: 'place.nadapuram', value: '1166' },
    { text: 'Naduvannur', textLocale: 'place.naduvannur', value: '1167' },
    { text: 'Nallalam', textLocale: 'place.nallalam', value: '1168' },
    { text: 'Nanmanda', textLocale: 'place.nanmanda', value: '1169' },
    { text: 'Narikkuni', textLocale: 'place.narikkuni', value: '1171' },
    { text: 'Olavanna', textLocale: 'place.olavanna', value: '1172' },
    { text: 'Omassery', textLocale: 'place.omassery', value: '1173' },
    { text: 'Orkkatteri', textLocale: 'place.orkkatteri', value: '1174' },
    { text: 'Padanilam', textLocale: 'place.padanilam', value: '1175' },
    { text: 'Panangad', textLocale: 'place.panangad', value: '1176' },
    { text: 'Panniyankara', textLocale: 'place.panniyankara', value: '1177' },
    { text: 'Pantheeramkavu', textLocale: 'place.pantheeramkavu', value: '1178' },
    { text: 'Parambil Bazar', textLocale: 'place.parambil_bazar', value: '1180' },
    { text: 'Pavangad', textLocale: 'place.pavangad', value: '1181' },
    { text: 'Payyoli', textLocale: 'place.payyoli', value: '1182' },
    { text: 'Perambra', textLocale: 'place.perambra', value: '1183' },
    { text: 'Perumanna', textLocale: 'place.perumanna', value: '1184' },
    { text: 'Peruvayal', textLocale: 'place.peruvayal', value: '1185' },
    { text: 'Poolacode', textLocale: 'place.poolacode', value: '1186' },
    { text: 'Poonoor', textLocale: 'place.poonoor', value: '1187' },
    { text: 'Puthiyangadi', textLocale: 'place.puthiyangadi', value: '1188' },
    { text: 'Puthiyarakozhikode', textLocale: 'place.puthiyarakozhikode', value: '1189' },
    { text: 'Quilandy', textLocale: 'place.quilandy', value: '1190' },
    { text: 'Ramanattukara', textLocale: 'place.ramanattukara', value: '1191' },
    { text: 'Thalakkulathur', textLocale: 'place.thalakkulathur', value: '1192' },
    { text: 'Thalayad', textLocale: 'place.thalayad', value: '1193' },
    { text: 'Thamarassery', textLocale: 'place.thamarassery', value: '1194' },
    { text: 'Thazhecode', textLocale: 'place.thazhecode', value: '1195' },
    { text: 'Theekkuni', textLocale: 'place.theekkuni', value: '1196' },
    { text: 'Thikkody', textLocale: 'place.thikkody', value: '1197' },
    { text: 'Thiruvallur', textLocale: 'place.thiruvallur', value: '1198' },
    { text: 'Thiruvambady', textLocale: 'place.thiruvambady', value: '1199' },
    { text: 'Thodannur', textLocale: 'place.thodannur', value: '11100' },
    { text: 'Thottilpalam', textLocale: 'place.thottilpalam', value: '11101' },
    { text: 'Thuneri', textLocale: 'place.thuneri', value: '11102' },
    { text: 'Thurayur', textLocale: 'place.thurayur', value: '11103' },
    { text: 'Ulliyeri', textLocale: 'place.ulliyeri', value: '11104' },
    { text: 'Vadakara', textLocale: 'place.vadakara', value: '11105' },
    { text: 'Valayam', textLocale: 'place.valayam', value: '11106' },
    { text: 'valluvambram', textLocale: 'place.valluvambram', value: '11107' },
    { text: 'Vanimal', textLocale: 'place.vanimal', value: '11108' },
    { text: 'Villiappally', textLocale: 'place.villiappally', value: '11109' },
    { text: 'West Hill', textLocale: 'place.west_hill', value: '11110' },
  ],
  '13': [
    { text: 'Alakode', textLocale: 'place.alakode', value: '131' },
    { text: 'Anjarakandy', textLocale: 'place.anjarakandy', value: '132' },
    { text: 'Azhikode', textLocale: 'place.azhikode', value: '133' },
    { text: 'Azhikode North', textLocale: 'place.azhikode_north', value: '134' },
    { text: 'Azhikode South', textLocale: 'place.azhikode_south', value: '135' },
    { text: 'Chakkarakkal', textLocale: 'place.chakkarakkal', value: '136' },
    { text: 'Chalad', textLocale: 'place.chalad', value: '137' },
    { text: 'Chalode', textLocale: 'place.chalode', value: '138' },
    { text: 'Cheleri', textLocale: 'place.cheleri', value: '139' },
    { text: 'Chelora', textLocale: 'place.chelora', value: '1310' },
    { text: 'Chempanthotty', textLocale: 'place.chempanthotty', value: '1311' },
    { text: 'Chemperi', textLocale: 'place.chemperi', value: '1312' },
    { text: 'Cherukunnu', textLocale: 'place.cherukunnu', value: '1313' },
    { text: 'Cherupuzha', textLocale: 'place.cherupuzha', value: '1314' },
    { text: 'Cheruthazham', textLocale: 'place.cheruthazham', value: '1315' },
    { text: 'Chirakka', textLocale: 'place.chirakka', value: '1316' },
    { text: 'Chirakkal', textLocale: 'place.chirakkal', value: '1317' },
    { text: 'Chockli', textLocale: 'place.chockli', value: '1318' },
    { text: 'Chovva', textLocale: 'place.chovva', value: '1319' },
    { text: 'Dharmadam', textLocale: 'place.dharmadam', value: '1320' },
    { text: 'Edakkad', textLocale: 'place.edakkad', value: '1322' },
    { text: 'Elayavoor', textLocale: 'place.elayavoor', value: '1323' },
    { text: 'Eranholi', textLocale: 'place.eranholi', value: '1325' },
    { text: 'Eruvatti', textLocale: 'place.eruvatti', value: '1326' },
    { text: 'Ezhome', textLocale: 'place.ezhome', value: '1327' },
    { text: 'Irikkur', textLocale: 'place.irikkur', value: '1328' },
    { text: 'Irinave', textLocale: 'place.irinave', value: '1329' },
    { text: 'Iritty', textLocale: 'place.iritty', value: '1330' },
    { text: 'Iriveri', textLocale: 'place.iriveri', value: '1331' },
    { text: 'Kadachira', textLocale: 'place.kadachira', value: '1332' },
    { text: 'Kadannappalli', textLocale: 'place.kadannappalli', value: '1333' },
    { text: 'Kadirur', textLocale: 'place.kadirur', value: '1334' },
    { text: 'Kakkadkannur', textLocale: 'place.kakkadkannur', value: '1335' },
    { text: 'Kalliasseri', textLocale: 'place.kalliasseri', value: '1336' },
    { text: 'Kandamkunnu', textLocale: 'place.kandamkunnu', value: '1337' },
    { text: 'Kanhirode', textLocale: 'place.kanhirode', value: '1338' },
    { text: 'Kanichar', textLocale: 'place.kanichar', value: '1339' },
    { text: 'Kannadiparamba', textLocale: 'place.kannadiparamba', value: '1340' },
    { text: 'Kannapuram', textLocale: 'place.kannapuram', value: '1341' },
    { text: 'Kannur', textLocale: 'place.kannur', value: '1342' },
    { text: 'Kannur Cantonment', textLocale: 'place.kannur_cantonment', value: '1343' },
    { text: 'Karivellur', textLocale: 'place.karivellur', value: '1344' },
    { text: 'Karuvanchal', textLocale: 'place.karuvanchal', value: '1345' },
    { text: 'Keezhallur', textLocale: 'place.keezhallur', value: '1346' },
    { text: 'Kelakam', textLocale: 'place.kelakam', value: '1347' },
    { text: 'Kolacherry', textLocale: 'place.kolacherry', value: '1348' },
    { text: 'Kolavelloor', textLocale: 'place.kolavelloor', value: '1349' },
    { text: 'Kolayad', textLocale: 'place.kolayad', value: '1350' },
    { text: 'Koodali', textLocale: 'place.koodali', value: '1351' },
    { text: 'Koothuparamba', textLocale: 'place.koothuparamba', value: '1352' },
    { text: 'Kottayam Malabar', textLocale: 'place.kottayam_malabar', value: '1353' },
    { text: 'Kottiyoor', textLocale: 'place.kottiyoor', value: '1354' },
    { text: 'Kunhimangalam', textLocale: 'place.kunhimangalam', value: '1355' },
    { text: 'Kurumathur', textLocale: 'place.kurumathur', value: '1356' },
    { text: 'Kuthuparamba', textLocale: 'place.kuthuparamba', value: '1357' },
    { text: 'Kuttiattoor', textLocale: 'place.kuttiattoor', value: '1358' },
    { text: 'Madayi', textLocale: 'place.madayi', value: '1359' },
    { text: 'Mahe', textLocale: 'place.mahe', value: '1360' },
    { text: 'Manakkadavu', textLocale: 'place.manakkadavu', value: '1361' },
    { text: 'Manantheri', textLocale: 'place.manantheri', value: '1362' },
    { text: 'Mangattidam', textLocale: 'place.mangattidam', value: '1364' },
    { text: 'Maniyoor', textLocale: 'place.maniyoor', value: '1365' },
    { text: 'Mattannur', textLocale: 'place.mattannur', value: '1366' },
    { text: 'Mattool', textLocale: 'place.mattool', value: '1368' },
    { text: 'Mavilayi', textLocale: 'place.mavilayi', value: '1369' },
    { text: 'Mayyil', textLocale: 'place.mayyil', value: '1370' },
    { text: 'Mokeri', textLocale: 'place.mokeri', value: '1371' },
    { text: 'Muzhappilangad', textLocale: 'place.muzhappilangad', value: '1372' },
    { text: 'Naduvil', textLocale: 'place.naduvil', value: '1373' },
    { text: 'Narath', textLocale: 'place.narath', value: '1374' },
    { text: 'New Mahe', textLocale: 'place.new_mahe', value: '1375' },
    { text: 'Paduvilayi', textLocale: 'place.paduvilayi', value: '1376' },
    { text: 'Palayad', textLocale: 'place.palayad', value: '1377' },
    { text: 'Pallikkunnu', textLocale: 'place.pallikkunnu', value: '1379' },
    { text: 'Panniyannur', textLocale: 'place.panniyannur', value: '1380' },
    { text: 'Panoor', textLocale: 'place.panoor', value: '1381' },
    { text: 'Pappinisseri', textLocale: 'place.pappinisseri', value: '1383' },
    { text: 'Parassinikadavu', textLocale: 'place.parassinikadavu', value: '1384' },
    { text: 'Pariyaram', textLocale: 'place.pariyaram', value: '1385' },
    { text: 'Pathiriyad', textLocale: 'place.pathiriyad', value: '1386' },
    { text: 'Payyannur', textLocale: 'place.payyannur', value: '1388' },
    { text: 'Payyavoor', textLocale: 'place.payyavoor', value: '1390' },
    { text: 'Pazhayangadi', textLocale: 'place.pazhayangadi', value: '1391' },
    { text: 'Peralasseri', textLocale: 'place.peralasseri', value: '1392' },
    { text: 'Peringathur', textLocale: 'place.peringathur', value: '1393' },
    { text: 'Pilathara', textLocale: 'place.pilathara', value: '1394' },
    { text: 'Pinarayi', textLocale: 'place.pinarayi', value: '1395' },
    { text: 'Puthiyatheru', textLocale: 'place.puthiyatheru', value: '1396' },
    { text: 'Puzhathi', textLocale: 'place.puzhathi', value: '1397' },
    { text: 'Sreekandapuram', textLocale: 'place.sreekandapuram', value: '1398' },
    { text: 'Taliparamba', textLocale: 'place.taliparamba', value: '1399' },
    { text: 'Thalassery', textLocale: 'place.thalassery', value: '13101' },
    { text: 'Thana', textLocale: 'place.thana', value: '13102' },
    { text: 'Thottada', textLocale: 'place.thottada', value: '13104' },
    { text: 'Udayagiri', textLocale: 'place.udayagiri', value: '13105' },
    { text: 'Ulikkal', textLocale: 'place.ulikkal', value: '13106' },
    { text: 'Valapattanam', textLocale: 'place.valapattanam', value: '13108' },
    { text: 'Varam', textLocale: 'place.varam', value: '13109' },
  ],
};

export const RELIGIONS: DropdownItem[] = [
  { text: 'Christian', textLocale: 'rel.christian', value: '1' },
  { text: 'Hindu', textLocale: 'rel.hindu', value: '2' },
  { text: 'Inter Religion', textLocale: 'rel.inter_religion', value: '3' },
  { text: 'Muslim', textLocale: 'rel.muslim', value: '4' },
  { text: 'No Religion', textLocale: 'rel.no_religion', value: '5' },
  { text: 'Others', textLocale: 'rel.others', value: '6' },
  { text: 'Buddhist', textLocale: 'rel.buddhist', value: '7' },
  { text: 'Bahai', textLocale: 'rel.bahai', value: '8' },
  { text: 'Jainism', textLocale: 'rel.jainism', value: '9' },
  { text: 'Jewish', textLocale: 'rel.jewish', value: '10' },
  { text: 'Parsi', textLocale: 'rel.parsi', value: '11' },
  { text: 'Shintoism', textLocale: 'rel.shintoism', value: '12' },
  { text: 'Sikhism', textLocale: 'rel.sikhism', value: '13' },
  { text: 'Taoism', textLocale: 'rel.taoism', value: '14' },
];

// Sects keyed by religion value — currently only Muslim (value '4') has sect data
export const SECTS: Record<string, DropdownItem[]> = {
  '4': [
    { text: 'A Muslim (Sect-neutral)', textLocale: 'mes_sec.a_muslim_sect_neutral', value: '1' },
    { text: 'Sunni', textLocale: 'mes_sec.sunni', value: '2' },
    { text: 'Salafi', textLocale: 'mes_sec.salafi', value: '3' },
    { text: 'Jamat Islami', textLocale: 'mes_sec.jamat_islami', value: '4' },
    { text: 'Thableegh Jamaat', textLocale: 'mes_sec.thableegh_jamaat', value: '5' },
    { text: 'Sufism', textLocale: 'mes_sec.sufism', value: '6' },
    { text: 'Shia', textLocale: 'mes_sec.shia', value: '7' },
    { text: 'Shafi', textLocale: 'mes_sec.shafi', value: '8' },
    { text: 'Hanafi', textLocale: 'mes_sec.hanafi', value: '9' },
    { text: 'Hanabali', textLocale: 'mes_sec.hanabali', value: '10' },
    { text: 'Maliki', textLocale: 'mes_sec.maliki', value: '11' },
    { text: 'Urdu Muslim', textLocale: 'mes_sec.urdu_muslim', value: '12' },
    { text: 'Sayyid', textLocale: 'mes_sec.sayyid', value: '13' },
    { text: 'Bohra', textLocale: 'mes_sec.bohra', value: '14' },
    { text: 'Pathan', textLocale: 'mes_sec.pathan', value: '15' },
    { text: 'Ahle Hadees', textLocale: 'mes_sec.ahle_hadees', value: '16' },
    { text: 'Ahamadi', textLocale: 'mes_sec.ahamadi', value: '17' },
    { text: 'Ibadi', textLocale: 'mes_sec.ibadi', value: '18' },
    { text: 'Ismaili', textLocale: 'mes_sec.ismaili', value: '19' },
    { text: 'Zahiri', textLocale: 'mes_sec.zahiri', value: '20' },
    { text: 'Sunni (AP)', textLocale: 'mes_sec.sunni_ap', value: '21' },
    { text: 'Sunni (EK)', textLocale: 'mes_sec.sunni_ek', value: '22' },
    { text: 'Salafi (KNM)', textLocale: 'mes_sec.salafi_knm', value: '23' },
    { text: 'Salafi (Wisdom)', textLocale: 'mes_sec.salafi_wisdom', value: '24' },
    { text: 'Salafi (Markaz Dawa)', textLocale: 'mes_sec.salafi_markaz_dawa', value: '25' },
    { text: 'Other', textLocale: 'mes_sec.other', value: '26' },
    { text: 'Prefer not to say', textLocale: 'mes_sec.prefer_not_to_say', value: '27' },
  ],
};

export const MARITAL_STATUSES: DropdownItem[] = [
  { text: 'Single', textLocale: 'status.single', value: '1' },
  { text: 'Widow', textLocale: 'status.widow', value: '2' },
  { text: 'Divorced', textLocale: 'status.divorced', value: '3' },
  { text: 'Nikah Divorce', textLocale: 'status.nikah_divorce', value: '6' },
  { text: 'Awaiting Divorce', textLocale: 'status.awaiting_divorce', value: '5' },
  { text: 'Separated', textLocale: 'status.separated', value: '7' },
  { text: 'Married', textLocale: 'status.married', value: '4' },
  { text: 'Annulled', textLocale: 'status.annulled', value: '8' },
];

// Heights: 140–220 cm range (practical range for marriage profiles)
export const HEIGHTS: HeightItem[] = [
  { text: "140 cm", value: '140' },
  { text: "141 cm (4'7\")", value: '141' },
  { text: "142 cm", value: '142' },
  { text: "143 cm", value: '143' },
  { text: "144 cm (4'8\")", value: '144' },
  { text: "145 cm", value: '145' },
  { text: "146 cm", value: '146' },
  { text: "147 cm (4'9\")", value: '147' },
  { text: "148 cm", value: '148' },
  { text: "149 cm", value: '149' },
  { text: "150 cm (5')", value: '150' },
  { text: "151 cm", value: '151' },
  { text: "152 cm", value: '152' },
  { text: "153 cm (5'1\")", value: '153' },
  { text: "154 cm", value: '154' },
  { text: "155 cm", value: '155' },
  { text: "156 cm (5'2\")", value: '156' },
  { text: "157 cm", value: '157' },
  { text: "158 cm", value: '158' },
  { text: "159 cm (5'3\")", value: '159' },
  { text: "160 cm", value: '160' },
  { text: "161 cm", value: '161' },
  { text: "162 cm (5'4\")", value: '162' },
  { text: "163 cm", value: '163' },
  { text: "164 cm", value: '164' },
  { text: "165 cm (5'5\")", value: '165' },
  { text: "166 cm", value: '166' },
  { text: "167 cm", value: '167' },
  { text: "168 cm (5'6\")", value: '168' },
  { text: "169 cm", value: '169' },
  { text: "170 cm", value: '170' },
  { text: "171 cm (5'7\")", value: '171' },
  { text: "172 cm", value: '172' },
  { text: "173 cm", value: '173' },
  { text: "174 cm (5'8\")", value: '174' },
  { text: "175 cm", value: '175' },
  { text: "176 cm", value: '176' },
  { text: "177 cm (5'9\")", value: '177' },
  { text: "178 cm", value: '178' },
  { text: "179 cm", value: '179' },
  { text: "180 cm (6')", value: '180' },
  { text: "181 cm", value: '181' },
  { text: "182 cm", value: '182' },
  { text: "183 cm (6'1\")", value: '183' },
  { text: "184 cm", value: '184' },
  { text: "185 cm", value: '185' },
  { text: "186 cm (6'2\")", value: '186' },
  { text: "187 cm", value: '187' },
  { text: "188 cm", value: '188' },
  { text: "189 cm (6'3\")", value: '189' },
  { text: "190 cm", value: '190' },
  { text: "191 cm", value: '191' },
  { text: "192 cm", value: '192' },
  { text: "193 cm (6'4\")", value: '193' },
  { text: "194 cm", value: '194' },
  { text: "195 cm", value: '195' },
  { text: "196 cm (6'5\")", value: '196' },
  { text: "197 cm", value: '197' },
  { text: "198 cm", value: '198' },
  { text: "199 cm (6'6\")", value: '199' },
  { text: "200 cm", value: '200' },
  { text: "201 cm", value: '201' },
  { text: "202 cm (6'7\")", value: '202' },
  { text: "203 cm", value: '203' },
  { text: "204 cm", value: '204' },
  { text: "205 cm (6'8\")", value: '205' },
];

// Weights: 40–130 kg
export const WEIGHTS: WeightItem[] = Array.from({ length: 91 }, (_, i) => ({
  text: `${40 + i} Kg`,
  value: String(40 + i),
}));
